### ISSUE TITLE
bounce2.h

### ISSUE THREAD

**Issue by ahmedhessin** [lendres/ButtonSuite-Arduino#1]
when compiling an error message occurs "fatal error : no such file or directory

**Comment by lendres** [comment]
Please note there are prerequisites required; ensure you have all those libraries installed.  The list of required libraries can be found in the source code.

**Comment by ahmedhessin** [comment]
I have installed the required libraries and it worked well Thank you so much 🤗

Sent from Yahoo Mail on Android 
 
  On الخميس, يونيو ١٧, ٢٠٢١ at ٥:١٦ م, Lance A. ***@***.***> wrote:   


First, please note there are prerequisites required; ensure you have all those libraries installed. The list of required libraries can be found in the source code. If that doesn't work, you will have to provide more information such as which files or directories are missing, did you check to see if those files are included in the download, et cetera.

**Comment by lendres** [comment]
Excellent!  Enjoy!
