### ISSUE TITLE
Demo_03

### ISSUE THREAD

**Issue by gmglickman** [lendres/ButtonSuite-Arduino#2]
Doesn't Demo_03 trigger on both press and release with CAPTUREBOTH?
comments say: 	// This will return true only once for each button push.
	// This example is triggered on the press of the button.  As soon as the button is pressed down
	// this returns true.  It does not matter how long the button is held down, the light flashes
	// for the same amount of time.  Nothing happens on the button release.

**Comment by lendres** [comment]
The comment was incorrect.  It has been fixed.  Thanks for catching this.
