### ISSUE TITLE
Compilation warning on Raspberry Pico W board

### ISSUE THREAD

**Issue by woodlist** [lendres/ButtonSuite-Arduino#4]
The library is ok on ESP32 platform, on Arduino IDE 2.3.2. Tried to port the sketch on Raspberry Pico W and got the following warning:
`c:\Users\woodl\Documents\Arduino\libraries\ButtonSuite\src\ButtonBase.cpp: In member function 'BUTTONSUITE::BUTTONSTATUS ButtonBase::update()':
c:\Users\woodl\Documents\Arduino\libraries\ButtonSuite\src\ButtonBase.cpp:82:40: warning: 'long unsigned int Debouncer::duration()' is deprecated [-Wdeprecated-declarations]
   82 |                 if (_debouncer.duration() < _longPressInterval)
      |                     ~~~~~~~~~~~~~~~~~~~^~
In file included from c:\Users\woodl\Documents\Arduino\libraries\ButtonSuite\src\ButtonBase.h:62,
                 from c:\Users\woodl\Documents\Arduino\libraries\ButtonSuite\src\ButtonBase.cpp:24:
c:\Users\woodl\Documents\Arduino\libraries\Bounce2\src/Bounce2.h:164:19: note: declared here
  164 |     unsigned long duration() {
      |                   ^~~~~~~~`

**Comment by lendres** [comment]
The debouncer library is separate (outside of my control).  Please refer to:
https://github.com/thomasfredericks/Bounce2

Deprecated means updates should be made in the future but are not strictly speaking required now.  As this is a warning, it should work for the time being.

I wholeheartedly support your efforts to port to the Raspberry platform.  However, I do not personally plan to support the platform.  If there is not an issue on the Arduino platform, there likely isn't much I can do.  If you wish to determine the cause and issue a pull request, that would be great.

If you get your port working, please let me know and I will include a link to it!

**Comment by woodlist** [comment]
This issue has been fixed as below written:
In ButtonBase.cpp:82
was `if (_debouncer.duration() < _longPressInterval)`
Now it should be `if (_debouncer.currentDuration() < _longPressInterval)`

**Comment by lendres** [comment]
Ah, I see.  Thanks for the information!  I have updated the library and added a new release.
